# name: Deploy Static Website to S3

# on:
#   push:
#     branches:
#       - master  # Trigger the workflow when changes are pushed to the main branch

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Deploy to S3
#       uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --delete --cache-control "max-age=31536000"
#       env:
#         SOURCE_DIR: './'  # The directory containing index.html and style.css
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}  # Name of your S3 bucket
#         AWS_REGION: 'us-west-1'  # Optional, specify if needed
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
